openapi: 3.0.0
info:
  title: QR Ad Service API
  version: 1.0.0
  description: API for managing QR Code Ad Service

servers:
  - url: /api/v1

paths:
  /auth/register:
    post:
      summary: Register a new owner account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Account created successfully
        '400':
          description: Bad Request

  /auth/login:
    post:
      summary: Login an owner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /owners/summary:
    get:
      summary: Get owner account summary
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountSummary'
        '401':
          description: Unauthorized

  /owners/qrcode:
    post:
      summary: Generate a new QR code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateQRCodeRequest'
      responses:
        '201':
          description: QR code generated successfully

  /admin/stats:
    get:
      summary: Get system statistics for admin
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminStats'

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        businessName:
          type: string
      required:
        - email
        - password
        - businessName

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    AccountSummary:
      type: object
      properties:
        totalClicks:
          type: integer
        totalRevenue:
          type: number

    GenerateQRCodeRequest:
      type: object
      properties:
        originalUrl:
          type: string
        qrCodeFile:
          type: string
      required:
        - originalUrl

    AdminStats:
      type: object
      properties:
        totalUsers:
          type: integer
        totalRevenue:
          type: number
        totalAdsServed:
          type: integer
        totalClicks:
          type: integer