package models

import (
	"time"
)

// User represents an owner of the QR codes.
type User struct {
	ID           int64     `json:"id" gorm:"primaryKey"`
	Email        string    `json:"email" gorm:"uniqueIndex;not null"`
	PasswordHash string    `json:"-" gorm:"not null"`
	BusinessName string    `json:"business_name" gorm:"not null"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// QRCode represents a QR code generated by an owner.
type QRCode struct {
	ID            int64     `json:"id" gorm:"primaryKey"`
	OriginalURL   string    `json:"original_url" gorm:"not null"`
	GeneratedCode string    `json:"generated_code" gorm:"not null"`
	UserID        int64     `json:"user_id" gorm:"index;not null"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// AdLog represents an ad view or click event.
type AdLog struct {
	ID        int64     `json:"id" gorm:"primaryKey"`
	QRCodeID  int64     `json:"qr_code_id" gorm:"index;not null"`
	IsClicked bool      `json:"is_clicked" gorm:"not null"`
	Revenue   float64   `json:"revenue" gorm:"not null"`
	CreatedAt time.Time `json:"created_at"`
}

// Revenue represents the revenue shared with an owner.
type Revenue struct {
	ID        int64     `json:"id" gorm:"primaryKey"`
	UserID    int64     `json:"user_id" gorm:"index;not null"`
	Amount    float64   `json:"amount" gorm:"not null"`
	CreatedAt time.Time `json:"created_at"`
}
