// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

// AccountSummary defines model for AccountSummary.
type AccountSummary struct {
	TotalClicks  *int     `json:"totalClicks,omitempty"`
	TotalRevenue *float32 `json:"totalRevenue,omitempty"`
}

// AdminStats defines model for AdminStats.
type AdminStats struct {
	TotalAdsServed *int     `json:"totalAdsServed,omitempty"`
	TotalClicks    *int     `json:"totalClicks,omitempty"`
	TotalRevenue   *float32 `json:"totalRevenue,omitempty"`
	TotalUsers     *int     `json:"totalUsers,omitempty"`
}

// GenerateQRCodeRequest defines model for GenerateQRCodeRequest.
type GenerateQRCodeRequest struct {
	OriginalUrl string  `json:"originalUrl"`
	QrCodeFile  *string `json:"qrCodeFile,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	BusinessName string `json:"businessName"`
	Email        string `json:"email"`
	Password     string `json:"password"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostOwnersQrcodeJSONRequestBody defines body for PostOwnersQrcode for application/json ContentType.
type PostOwnersQrcodeJSONRequestBody = GenerateQRCodeRequest
