package handlers

import (
	"net/http"

	"github.com/gmgale/qr-ad-service/internal/api"
	"github.com/go-chi/chi/v5"
)

// Implement the interface generated by oapi-codegen
type Server struct{}

// Get owner account summary
func (s *Server) GetOwnersSummary(w http.ResponseWriter, r *http.Request) {
	// Implementation here
}

// Get system statistics for admin
func (s *Server) GetAdminStats(w http.ResponseWriter, r *http.Request) {
	// Implementation here
}

// Wire up the server with the routes
func SetupRouter() chi.Router {
	r := chi.NewRouter()
	s := &Server{}

	api.HandlerFromMux(s, r)

	return r
}
